'use strict';
const assert = require('assert');
const fs = require('fs');
const os = require('os');
const path = require('path');
const content = require('../lib/minecraft-content.cjs');
const curseforge = require('../lib/curseforge-import.cjs');
const ftb = require('../lib/ftb-installer.cjs');
const apply = require('../lib/content-apply.cjs');
assert.deepStrictEqual(content.listProviders().map((p) => p.id), ['modrinth', 'curseforge', 'ftb']);
assert.strictEqual(content.provider('curseforge').capabilities.catalog, false);
assert.strictEqual(content.listProviders().find((p) => p.id === 'ftb').capabilities.executeAvailable, false);
assert.strictEqual(content.normalizeProject({ project_id: 'p', project_type: 'mod', title: 'Test' }).kind, 'mod');
assert.deepStrictEqual(curseforge.unresolvedReferences({ files: [{ projectID: 12, fileID: 34 }, { projectID: 56 }] }), ['12:34']);
assert.strictEqual(curseforge.commonRoot(['Pack/manifest.json', 'Pack/mods/a.jar']), 'Pack');
assert.strictEqual(curseforge.commonRoot(['manifest.json', 'mods/a.jar']), '');
assert.strictEqual(curseforge.stripCommonRoot('Pack\\mods\\a.jar', 'Pack'), 'mods/a.jar');
assert.strictEqual(ftb.platformAsset({ platform: 'win32', arch: 'x64' }).os, 'windows');
assert.deepStrictEqual(ftb.buildArgs({ stagingDir: '.', packId: 100, latest: true }).slice(-2), ['100', '-latest']);
assert.ok(ftb.buildArgs({ stagingDir: '.', packId: 100, versionId: 200, acceptEula: true }).includes('-accept-eula'));
assert.throws(() => ftb.buildArgs({ stagingDir: '.', packId: 'oops', latest: true }), /numeric FTB pack ID/);
assert.throws(() => ftb.selectReleaseAsset({ assets: [{ name: 'server-installer-windows-x64.exe' }] }, { platform: 'win32', arch: 'x64' }), /SHA-256/);
assert.deepStrictEqual(apply.curseManifestMeta({ name: 'Pack', version: '1.0', minecraft: { version: '1.20.1', modLoaders: [{ id: 'forge-47.2.0', primary: true }] } }), { displayName: 'Pack', versionName: '1.0', mcVersion: '1.20.1', loader: 'forge', overridesDir: 'overrides' });
assert.strictEqual(apply.curseDeployPath('manifest.json'), null);
assert.strictEqual(apply.curseDeployPath('overrides/mods/a.jar'), 'mods/a.jar');
assert.strictEqual(apply.curseDeployPath('mods/a.jar'), 'mods/a.jar');
assert.strictEqual(apply.normalizeRelative('../escape.jar'), null);
assert.ok(apply.safeResolve('/srv/pack', 'mods/a.jar').endsWith(path.join('mods', 'a.jar')));
assert.strictEqual(apply.safeResolve('/srv/pack', '../escape.jar'), null);
assert.throws(() => apply.checkDecisions({ groups: { conflicts: [{ relativePath: 'mods/a.jar' }] } }, {}), /decision is required/);
apply.checkDecisions({ groups: { conflicts: [{ relativePath: 'mods/a.jar' }] } }, { 'mods/a.jar': 'take_pack' });
{
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'content-apply-'));
  fs.mkdirSync(path.join(tmp, 'mods'), { recursive: true });
  fs.writeFileSync(path.join(tmp, 'mods', 'a.jar'), 'hello');
  const walked = apply.walkStaging(tmp);
  assert.strictEqual(walked.length, 1);
  assert.strictEqual(walked[0].relativePath, 'mods/a.jar');
  assert.ok(/^[a-f0-9]{64}$/.test(walked[0].sha256));
  fs.rmSync(tmp, { recursive: true, force: true });
}
console.log('ok  minecraft content provider contracts');
