'use strict';

/*
 * Terraria world creation, import and selection (docs/terraria/03-worlds.md).
 *
 * The acceptance list in that phase is the test list: a header that accepts real
 * worlds and refuses everything else, names that cannot escape the save
 * directory, companions that travel with their world, offline-only mutations,
 * single-use previews, a selection that writes both halves or neither, an
 * archive import that is refused before anything is written, quarantine instead
 * of recursive deletion, and no absolute paths in any response.
 *
 * Nothing here reaches the network, and generation never runs a real Terraria
 * server: the process is injected, so the runner's contract - progress, cancel,
 * timeout, verify, promote - is what is under test rather than the game.
 */

const assert = require('assert');
const fs = require('fs');
const path = require('path');
const zlib = require('zlib');
const { setupDataDir, teardown, TMP_ROOT } = require('./_setup.cjs');
setupDataDir();

const { close, dbPath, open } = require('../lib/db.cjs');
const migrations = require('../lib/migrations.cjs');
const operations = require('../lib/operations.cjs');
const snapshots = require('../lib/snapshots.cjs');
const trash = require('../lib/trash.cjs');
const terrariaConfig = require('../lib/terraria-config.cjs');
const worlds = require('../lib/terraria-worlds.cjs');

global.fetch = () => { throw new Error('a test reached the network'); };

function fresh() {
  close();
  for (const ext of ['', '-wal', '-shm']) {
    const p = dbPath() + ext;
    if (fs.existsSync(p)) { try { fs.unlinkSync(p); } catch (_) { /* */ } }
  }
  migrations.runMigrations();
}
fresh();

const ROOT = fs.mkdtempSync(path.join(TMP_ROOT, 'terraria-worlds-'));
const ACTOR = 'actor-1';
let seq = 0;

const tests = [];
const test = (name, fn) => tests.push({ name, fn });

async function rejects(fn, code) {
  try { await fn(); }
  catch (err) {
    assert.strictEqual(err.code, code, `expected ${code}, got ${err.code}: ${err.message}`);
    assert.ok(err.message && err.message.length > 10, 'errors carry a readable message');
    return err;
  }
  assert.fail(`expected ${code}, but the call succeeded`);
  return null;
}

/* ------------------------------------------------------------- fixtures -- */

/*
 * A world file with a real header.
 *
 * The layout is the documented one every world since Terraria 1.3.0.1 carries:
 * an int32 format version, the ASCII signature "relogic", a file-type byte, a
 * revision counter and a flags qword. `readWorldHeader` reads exactly this much,
 * so this is the whole contract - and the negative fixtures below are what prove
 * it is not matching anything that merely looks close.
 */
function worldBuffer({ version = 279, signature = 'relogic', fileType = 2, revision = 3, favorite = false, extra = 4096 } = {}) {
  const header = Buffer.alloc(24 + extra);
  header.writeInt32LE(version, 0);
  Buffer.from(signature, 'ascii').copy(header, 4);
  header.writeUInt8(fileType, 11);
  header.writeUInt32LE(revision, 12);
  header.writeBigUInt64LE(favorite ? 1n : 0n, 16);
  // The rest is world data as far as this module is concerned.
  header.fill(0x2a, 24);
  return header;
}

/*
 * A world carrying a real header section, laid out exactly as a Terraria world
 * is: the section pointer table, the tile-frame-important bits, then the header
 * section itself. The layout was confirmed byte-for-byte against worlds
 * generated by a real 1.4.5.6 dedicated server (format 319), one per difficulty;
 * this builder is that layout, so a change to the parser that stops matching a
 * real file fails here rather than in front of an operator.
 */
function netString(value) {
  const body = Buffer.from(value, 'utf8');
  const length = [];
  let remaining = body.length;
  do {
    let byte = remaining & 0x7f;
    remaining >>>= 7;
    if (remaining) byte |= 0x80;
    length.push(byte);
  } while (remaining);
  return Buffer.concat([Buffer.from(length), body]);
}

function worldWithHeaderSection({
  version = 319, name = 'Fixture', seed = 'seed', gameMode = 0,
  width = 4200, height = 1200, sections = 11, tileMaskBits = 753, section0 = null,
} = {}) {
  const preamble = Buffer.alloc(24 + 2 + 4 * sections + 2 + Math.ceil(tileMaskBits / 8));
  preamble.writeInt32LE(version, 0);
  Buffer.from('relogic', 'ascii').copy(preamble, 4);
  preamble.writeUInt8(2, 11);
  preamble.writeUInt32LE(2, 12);
  preamble.writeBigUInt64LE(0n, 16);
  preamble.writeInt16LE(sections, 24);
  // Section 0 starts where the preamble ends; the rest of the table is not read.
  preamble.writeInt32LE(section0 == null ? preamble.length : section0, 26);
  preamble.writeInt16LE(tileMaskBits, 26 + 4 * sections);

  const numbers = Buffer.alloc(8 + 16 + 4 + 16 + 12);
  let at = 0;
  numbers.writeBigUInt64LE(1370094567425n, at); at += 8;   // world generator version
  at += 16;                                                 // guid
  numbers.writeInt32LE(17750398, at); at += 4;              // world id
  numbers.writeInt32LE(0, at); at += 4;                     // left
  numbers.writeInt32LE(width * 16, at); at += 4;            // right
  numbers.writeInt32LE(0, at); at += 4;                     // top
  numbers.writeInt32LE(height * 16, at); at += 4;           // bottom
  numbers.writeInt32LE(height, at); at += 4;                // height precedes width
  numbers.writeInt32LE(width, at); at += 4;
  numbers.writeInt32LE(gameMode, at);

  return Buffer.concat([preamble, netString(name), netString(seed), numbers, Buffer.alloc(512, 0x2a)]);
}

const CONFIG_TEXT = [
  '# Hostkind test config',
  'world=WORLDPATH/World.wld',
  'worldpath=WORLDPATH',
  'autocreate=2',
  'worldname=World',
  'maxplayers=8',
  'port=7777',
  'motd=Hello',
  '',
].join('\n');

/*
 * A Terraria server folder: an installation with a `worlds/` save directory, a
 * serverconfig.txt that points into it, and an executable the generation tests
 * can be pointed at without ever running it.
 */
function makeServer({ worldNames = ['World'], variant = 'vanilla', modData = false, config = CONFIG_TEXT, saveDir = 'worlds' } = {}) {
  const id = `srv-${++seq}`;
  const dir = path.join(ROOT, id);
  const save = path.join(dir, saveDir);
  fs.mkdirSync(save, { recursive: true });
  for (const name of worldNames) {
    fs.writeFileSync(path.join(save, `${name}.wld`), worldBuffer());
    if (modData) fs.writeFileSync(path.join(save, `${name}.twld`), Buffer.alloc(128, 7));
  }
  const executable = path.join(dir, 'TerrariaServer.bin.x86_64');
  fs.writeFileSync(executable, '#!/bin/false\n');
  const configFile = path.join(dir, 'serverconfig.txt');
  fs.writeFileSync(configFile, config.replaceAll('WORLDPATH', save));
  return {
    id,
    name: `Server ${id}`,
    type: 'terraria',
    dir,
    cwd: dir,
    executable,
    args: ['-config', configFile],
    port: 7777,
    terrariaVariant: variant,
    terrariaSaveDir: saveDir,
    terrariaWorld: worldNames.length ? { file: `${saveDir}/${worldNames[0]}.wld`, name: worldNames[0] } : null,
  };
}

// A descriptor store that behaves like config.json does: the runner writes
// through `saveDescriptor` and verifies through `readDescriptor`, and those must
// not be the same object.
function descriptorStore(desc, { failSave = false, failRevert = false } = {}) {
  const live = { ...desc };
  return {
    desc: live,
    saved: [],
    saveDescriptor(fields) {
      if (failSave) throw new Error('config.json is read-only in this test');
      for (const [key, value] of Object.entries(fields)) {
        if (value === null) delete live[key];
        else live[key] = value;
      }
      this.saved.push(fields);
    },
    readDescriptor() {
      if (failRevert) return { ...live, terrariaWorld: null };
      return JSON.parse(JSON.stringify(live));
    },
  };
}

const fakeManager = (status = 'offline') => ({ status });

function saveDirOf(desc) {
  return path.join(desc.dir, desc.terrariaSaveDir || 'worlds');
}

const configOf = (desc) => fs.readFileSync(path.join(desc.dir, 'serverconfig.txt'), 'utf8');

// A store-only zip built byte by byte. archiver normalizes `../` out of entry
// names and cannot emit a symlink entry, so a hostile archive built with it
// would silently test nothing.
function makeZip(dest, entries) {
  const chunks = [];
  const central = [];
  let offset = 0;
  const push = (buffer) => { chunks.push(buffer); offset += buffer.length; };
  for (const entry of entries) {
    const name = Buffer.from(entry.name, 'utf8');
    const data = Buffer.isBuffer(entry.data) ? entry.data : Buffer.from(entry.data == null ? '' : entry.data);
    const crc = zlib.crc32(data);
    const mode = entry.mode == null ? 0o100644 : entry.mode;
    const local = Buffer.alloc(30);
    local.writeUInt32LE(0x04034b50, 0);
    local.writeUInt16LE(20, 4);
    local.writeUInt32LE(crc, 14);
    local.writeUInt32LE(data.length, 18);
    local.writeUInt32LE(data.length, 22);
    local.writeUInt16LE(name.length, 26);
    const localOffset = offset;
    push(local); push(name); push(data);
    const record = Buffer.alloc(46);
    record.writeUInt32LE(0x02014b50, 0);
    record.writeUInt16LE((3 << 8) | 20, 4);
    record.writeUInt16LE(20, 6);
    record.writeUInt32LE(crc, 16);
    record.writeUInt32LE(data.length, 20);
    record.writeUInt32LE(data.length, 24);
    record.writeUInt16LE(name.length, 28);
    record.writeUInt32LE(mode * 0x10000, 38);
    record.writeUInt32LE(localOffset, 42);
    central.push(Buffer.concat([record, name]));
  }
  const centralOffset = offset;
  for (const record of central) push(record);
  const end = Buffer.alloc(22);
  end.writeUInt32LE(0x06054b50, 0);
  end.writeUInt16LE(central.length, 8);
  end.writeUInt16LE(central.length, 10);
  end.writeUInt32LE(offset - centralOffset, 12);
  end.writeUInt32LE(centralOffset, 16);
  push(end);
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.writeFileSync(dest, Buffer.concat(chunks));
  return dest;
}

// Stage an upload the way lib/routes/terraria.cjs does, without the HTTP layer.
function stageUpload(files, { kind = 'upload' } = {}) {
  const dir = worlds.importStagingDir(`stage-${++seq}`);
  fs.mkdirSync(path.join(dir, 'payload'), { recursive: true });
  for (const [name, data] of Object.entries(files)) {
    fs.writeFileSync(path.join(dir, 'payload', name), data);
  }
  return { dir, kind, archive: kind === 'archive' ? path.join('payload', 'upload.zip') : null, originalName: Object.keys(files)[0] };
}

// A generation that writes the world the real server would have written.
function generationStub({ produce = true, modData = false, fail = null, onSpawn = null } = {}) {
  return async ({ launch, onProgress, operationId }) => {
    if (onSpawn) onSpawn({ launch, operationId });
    onProgress({ percent: 0, stage: null });
    onProgress({ percent: 50, stage: 'Generating world terrain', stagePercent: 12 });
    if (fail) throw fail;
    if (produce) {
      // The staging config is what tells the server where to write, so the stub
      // reads it back rather than being told: a runner that stopped repointing
      // the config would fail here instead of passing.
      const document = terrariaConfig.parse(fs.readFileSync(launch.args[launch.args.indexOf('-config') + 1], 'utf8'));
      const target = terrariaConfig.get(document, 'world');
      fs.mkdirSync(path.dirname(target), { recursive: true });
      fs.writeFileSync(target, worldBuffer());
      if (modData) fs.writeFileSync(target.replace(/\.wld$/, '.twld'), Buffer.alloc(64, 3));
    }
    onProgress({ percent: 100, stage: 'Finalizing world', stagePercent: 0 });
    return { code: 0, signal: null, requestedExit: true, generating: true };
  };
}

const noAbsolutePaths = (value, label) => {
  const text = JSON.stringify(value);
  assert.ok(!text.includes(ROOT.replace(/\\/g, '\\\\')) && !text.includes(ROOT), `${label} leaked an absolute path`);
};

/* ------------------------------------------------------ 1. world headers -- */

test('the header accepts a world and refuses everything that is not one', () => {
  const good = worlds.readWorldHeader(worldBuffer({ version: 279, revision: 12, favorite: true }));
  assert.strictEqual(good.ok, true);
  assert.strictEqual(good.version, 279);
  assert.strictEqual(good.revision, 12);
  assert.strictEqual(good.favorite, true);
  // This buffer carries no header section, so the descriptive fields are
  // unknown - which is reported as unknown, never as a default.
  assert.strictEqual(good.gameMode, null);
  assert.strictEqual(good.worldName, null);
  assert.strictEqual(good.width, null);

  assert.strictEqual(worlds.readWorldHeader(worldBuffer().subarray(0, 12)).reason, 'truncated');
  assert.strictEqual(worlds.readWorldHeader(Buffer.alloc(0)).reason, 'truncated');
  assert.strictEqual(worlds.readWorldHeader(worldBuffer({ signature: 'relogiX' })).reason, 'not_a_world');
  assert.strictEqual(worlds.readWorldHeader(worldBuffer({ fileType: 1 })).reason, 'map_file');
  assert.strictEqual(worlds.readWorldHeader(worldBuffer({ fileType: 3 })).reason, 'player_file');
  // A valid signature with an implausible version is an unsupported version; a
  // file with no signature is simply not a world, whatever its first four bytes
  // happen to say.
  assert.strictEqual(worlds.readWorldHeader(worldBuffer({ version: 12 })).reason, 'unsupported_version');
});

test('the header section yields the world name, game mode and size', () => {
  // The four difficulties Hostkind offers, in the order Terraria stores them.
  // Confirmed against real generated worlds: classic 0, expert 1, master 2,
  // journey 3 - the same order `DIFFICULTIES` uses.
  const modes = ['classic', 'expert', 'master', 'journey'];
  modes.forEach((mode, value) => {
    const header = worlds.readWorldHeader(worldWithHeaderSection({ name: `World ${mode}`, gameMode: value }));
    assert.strictEqual(header.ok, true);
    assert.strictEqual(header.gameMode, mode, `game mode ${value} should read as ${mode}`);
    assert.strictEqual(header.worldName, `World ${mode}`);
    assert.strictEqual(header.width, 4200);
    assert.strictEqual(header.height, 1200);
  });

  const large = worlds.readWorldHeader(worldWithHeaderSection({ width: 8400, height: 2400 }));
  assert.strictEqual(large.width, 8400);
  assert.strictEqual(large.height, 2400);

  // A non-ASCII name survives the round trip: the length prefix counts bytes,
  // not characters, and getting that wrong would truncate the name.
  const accented = worlds.readWorldHeader(worldWithHeaderSection({ name: 'Mundo Pequeno' }));
  assert.strictEqual(accented.worldName, 'Mundo Pequeno');
});

test('a header section that cannot be trusted reports unknown, not a guess', () => {
  // A format too old for the game-mode field still yields the name, which has
  // been the first field of the section since the signature block existed.
  const old = worlds.readWorldHeader(worldWithHeaderSection({ version: 194, name: 'Old World' }));
  assert.strictEqual(old.ok, true);
  assert.strictEqual(old.worldName, 'Old World');
  assert.strictEqual(old.gameMode, null);

  // A mode outside the four that exist means the walk landed somewhere wrong.
  const bogusMode = worlds.readWorldHeader(worldWithHeaderSection({ gameMode: 47 }));
  assert.strictEqual(bogusMode.ok, true);
  assert.strictEqual(bogusMode.gameMode, null);

  // As does an implausible world size.
  const bogusSize = worlds.readWorldHeader(worldWithHeaderSection({ width: 3, height: 1 }));
  assert.strictEqual(bogusSize.gameMode, null);
  assert.strictEqual(bogusSize.width, null);

  // A section pointer past the end of what was read, and a section count that
  // is plainly garbage: both unknown, and neither an error - the file is still
  // a valid world by its signature.
  const beyond = worlds.readWorldHeader(worldWithHeaderSection({ section0: 900000 }));
  assert.strictEqual(beyond.ok, true);
  assert.strictEqual(beyond.worldName, null);

  // A pointer landing inside the preamble is equally wrong, in the other
  // direction: the header section can never start before the table that names it.
  const backwards = worlds.readWorldHeader(worldWithHeaderSection({ section0: 8 }));
  assert.strictEqual(backwards.ok, true);
  assert.strictEqual(backwards.worldName, null);

  const garbage = worldBuffer();
  garbage.writeInt16LE(9999, 24);
  assert.strictEqual(worlds.readWorldHeader(garbage).ok, true);
  assert.strictEqual(worlds.readWorldHeader(garbage).worldName, null);
});

test('a Minecraft level.dat and random bytes are not worlds', () => {
  // level.dat is gzip: 1f 8b 08 ...
  const levelDat = Buffer.concat([Buffer.from([0x1f, 0x8b, 0x08, 0x00]), Buffer.alloc(64, 9)]);
  assert.strictEqual(worlds.readWorldHeader(levelDat).ok, false);
  for (let i = 0; i < 25; i++) {
    const random = require('crypto').randomBytes(256);
    assert.strictEqual(worlds.readWorldHeader(random).ok, false, 'random bytes parsed as a world');
  }
});

/* ------------------------------------------------- 2. names and the save dir -- */

test('a world name may not escape the save directory', () => {
  for (const bad of ['../evil', '/etc/passwd', 'a/b', 'C:\\x', '..', '.', 'trailing.', 'x'.repeat(65), '']) {
    assert.throws(() => worlds.normalizeName(bad), /name|file/i, `accepted ${JSON.stringify(bad)}`);
  }
  assert.throws(() => worlds.normalizeName(`bad${String.fromCharCode(0)}name`));
  assert.throws(() => worlds.normalizeName(`bad${String.fromCharCode(9)}name`));
  assert.strictEqual(worlds.normalizeName(' My World '), 'My World');
});

test('reserved Windows device names are refused', () => {
  for (const bad of ['CON', 'con', 'lpt1', 'NUL', 'com9']) {
    assert.throws(() => worlds.normalizeName(bad), /reserved/i, `accepted ${bad}`);
  }
});

test('a request may only name a .wld inside the save directory', () => {
  for (const bad of ['../World.wld', 'worlds/World.wld', 'World.twld', 'World.wld.bak', 'serverconfig.txt', 'World']) {
    assert.throws(() => worlds.normalizeFile(bad), /file|name/i, `accepted ${bad}`);
  }
  assert.strictEqual(worlds.normalizeFile(' World.wld '), 'World.wld');
});

test('case-only collisions are refused on Windows semantics and allowed elsewhere', () => {
  assert.strictEqual(worlds.sameFile('World.wld', 'world.wld', { caseInsensitive: true }), true);
  assert.strictEqual(worlds.sameFile('World.wld', 'world.wld', { caseInsensitive: false }), false);

  // The collision check reads the directory, so a name differing only in case is
  // a collision exactly when the host would treat the two as one file.
  const desc = makeServer({ worldNames: ['World'] });
  const saveDir = worlds.resolveSaveDir(desc);
  assert.throws(() => worlds.previewGenerate({
    desc, actorId: ACTOR, input: { name: 'World', size: 'small' }, manager: fakeManager(),
  }), /already exists/);
  assert.ok(saveDir.rel === 'worlds');
});

test('the save directory comes from the descriptor, the config, or nowhere at all', () => {
  const fromDescriptor = makeServer();
  assert.strictEqual(worlds.resolveSaveDir(fromDescriptor).source, 'descriptor');
  assert.strictEqual(worlds.resolveSaveDir(fromDescriptor).rel, 'worlds');

  // No descriptor field: the server's own worldpath is authoritative.
  const fromConfig = makeServer();
  delete fromConfig.terrariaSaveDir;
  assert.strictEqual(worlds.resolveSaveDir(fromConfig).source, 'config');

  // Neither: refused with a reason, never defaulted to a guessed folder.
  const unknown = makeServer({ config: '# nothing here\nport=7777\n' });
  delete unknown.terrariaSaveDir;
  assert.throws(() => worlds.resolveSaveDir(unknown), (err) => err.code === 'save_dir_unknown');

  // A worldpath outside the server folder is not usable either.
  const outside = makeServer({ config: `worldpath=${path.join(ROOT, 'elsewhere')}\n` });
  delete outside.terrariaSaveDir;
  assert.throws(() => worlds.resolveSaveDir(outside), (err) => err.code === 'save_dir_unknown');
});

test('a save directory reached through a link is refused rather than followed', function () {
  const desc = makeServer({ worldNames: [] });
  const outside = path.join(ROOT, `link-target-${++seq}`);
  fs.mkdirSync(outside, { recursive: true });
  try { fs.symlinkSync(outside, path.join(desc.dir, 'linked')); }
  catch { return; } // unprivileged Windows: nothing to test
  desc.terrariaSaveDir = 'linked';
  assert.throws(() => worlds.resolveSaveDir(desc), (err) => err.code === 'symlink_path');
});

/* ---------------------------------------------------------- 3. inventory -- */

test('inventory lists worlds, companions and the active selection', () => {
  const desc = makeServer({ worldNames: ['World', 'Second'], modData: true });
  fs.writeFileSync(path.join(saveDirOf(desc), 'World.wld.bak'), worldBuffer());
  const inv = worlds.inventory(desc);

  assert.deepStrictEqual(inv.worlds.map((w) => w.file), ['Second.wld', 'World.wld']);
  const world = inv.worlds.find((w) => w.file === 'World.wld');
  assert.strictEqual(world.name, 'World');
  assert.strictEqual(world.hasModData, true);
  assert.strictEqual(world.hasBackup, true);
  assert.strictEqual(world.readable, true);
  assert.strictEqual(world.active, true);
  assert.strictEqual(world.header.version, 279);
  assert.strictEqual(inv.worlds.find((w) => w.file === 'Second.wld').active, false);
  assert.strictEqual(inv.saveDir, 'worlds');
  assert.strictEqual(inv.selection.disagrees, false);
});

test('a file that is not a readable world is listed as unreadable, never as a world', () => {
  const desc = makeServer({ worldNames: ['World'] });
  fs.writeFileSync(path.join(saveDirOf(desc), 'Broken.wld'), Buffer.alloc(8, 1));
  fs.writeFileSync(path.join(saveDirOf(desc), 'Future.wld'), worldBuffer({ signature: 'notreal' }));

  const inv = worlds.inventory(desc);
  assert.deepStrictEqual(inv.worlds.map((w) => w.file), ['World.wld']);
  assert.deepStrictEqual(inv.unreadable.map((u) => u.file).sort(), ['Broken.wld', 'Future.wld']);
  assert.strictEqual(inv.unreadable.find((u) => u.file === 'Broken.wld').reason, 'truncated');
  // Still on disk: an unreadable world is reported, not tidied away.
  assert.ok(fs.existsSync(path.join(saveDirOf(desc), 'Broken.wld')));
});

test('a config and descriptor naming different worlds is published as a disagreement', () => {
  const desc = makeServer({ worldNames: ['World', 'Second'] });
  desc.terrariaWorld = { file: 'worlds/Second.wld', name: 'Second' };
  const inv = worlds.inventory(desc);
  assert.strictEqual(inv.selection.descriptor, 'Second.wld');
  assert.strictEqual(inv.selection.config, 'World.wld');
  assert.strictEqual(inv.selection.disagrees, true);
});

test('responses carry no absolute paths', () => {
  const desc = makeServer({ worldNames: ['World'], modData: true });
  noAbsolutePaths(worlds.inventory(desc), 'inventory');
  noAbsolutePaths(worlds.previewSelect({ desc, actorId: ACTOR, file: 'World.wld', manager: fakeManager() }), 'select preview');
  noAbsolutePaths(worlds.previewDelete({ desc, actorId: ACTOR, file: 'World.wld', manager: fakeManager() }), 'delete preview');
  noAbsolutePaths(
    worlds.previewGenerate({ desc, actorId: ACTOR, input: { name: 'Fresh', size: 'small' }, manager: fakeManager() }),
    'generate preview',
  );
});

/* ------------------------------------------------------------ 4. previews -- */

test('a preview token is consumable once, by its own actor, for its own action', () => {
  const desc = makeServer({ worldNames: ['World'] });
  const preview = worlds.previewSelect({ desc, actorId: ACTOR, file: 'World.wld', manager: fakeManager() });

  assert.throws(() => worlds.consumePreview({ token: preview.token, desc, actorId: 'someone-else', action: 'terraria-select' }),
    (err) => err.code === 'preview_invalid');
  assert.throws(() => worlds.consumePreview({ token: preview.token, desc, actorId: ACTOR, action: 'terraria-delete' }),
    (err) => err.code === 'preview_invalid');

  const consumed = worlds.consumePreview({ token: preview.token, desc, actorId: ACTOR, action: 'terraria-select' });
  assert.strictEqual(consumed.world.file, 'World.wld');
  assert.throws(() => worlds.consumePreview({ token: preview.token, desc, actorId: ACTOR, action: 'terraria-select' }),
    (err) => err.code === 'preview_invalid');
});

test('a preview taken against a different world list is stale', () => {
  const desc = makeServer({ worldNames: ['World'] });
  const preview = worlds.previewSelect({ desc, actorId: ACTOR, file: 'World.wld', manager: fakeManager() });
  fs.writeFileSync(path.join(saveDirOf(desc), 'Sneaked.wld'), worldBuffer());
  assert.throws(() => worlds.consumePreview({ token: preview.token, desc, actorId: ACTOR, action: 'terraria-select' }),
    (err) => err.code === 'preview_stale');
});

test('an expired preview is refused', () => {
  const desc = makeServer({ worldNames: ['World'] });
  const preview = worlds.previewSelect({ desc, actorId: ACTOR, file: 'World.wld', manager: fakeManager() });
  open().prepare('UPDATE world_previews SET expires_at = ? WHERE token = ?').run(Date.now() - 1000, preview.token);
  assert.throws(() => worlds.consumePreview({ token: preview.token, desc, actorId: ACTOR, action: 'terraria-select' }),
    (err) => err.code === 'preview_expired');
});

/* ----------------------------------------------------------- 5. selection -- */

async function runOperation(kind, run) {
  const op = operations.create({ kind, actorId: ACTOR, serverId: `op-${++seq}` });
  operations.start(op.id, { phase: 'preview-revalidate' });
  try { return { id: op.id, result: await run(op.id) }; }
  catch (error) { return { id: op.id, error }; }
}

test('selection writes serverconfig.txt and the descriptor, and changes nothing else', async () => {
  const desc = makeServer({ worldNames: ['World', 'Second'] });
  const store = descriptorStore(desc);
  const before = configOf(desc);
  const preview = worlds.previewSelect({ desc: store.desc, actorId: ACTOR, file: 'Second.wld', manager: fakeManager() });
  worlds.consumePreview({ token: preview.token, desc: store.desc, actorId: ACTOR, action: 'terraria-select' });

  const { id, result, error } = await runOperation(worlds.KIND.SELECT, (operationId) => worlds.runSelect({
    desc: store.desc, manager: fakeManager(), operationId, preview,
    saveDescriptor: (fields) => store.saveDescriptor(fields),
    readDescriptor: () => store.readDescriptor(),
  }));
  assert.ifError(error);
  assert.strictEqual(result.file, 'Second.wld');
  assert.strictEqual(operations.get(id).state, 'succeeded');

  const after = configOf(desc);
  const beforeLines = before.split('\n');
  const afterLines = after.split('\n');
  assert.strictEqual(beforeLines.length, afterLines.length, 'the line count changed');
  for (let i = 0; i < beforeLines.length; i++) {
    if (beforeLines[i].startsWith('world=')) {
      assert.strictEqual(afterLines[i], `world=${path.join(saveDirOf(desc), 'Second.wld')}`);
    } else {
      assert.strictEqual(afterLines[i], beforeLines[i], `line ${i + 1} changed: ${beforeLines[i]}`);
    }
  }
  assert.strictEqual(store.desc.terrariaWorld.file, 'worlds/Second.wld');
  assert.strictEqual(store.desc.terrariaWorld.name, 'Second');
});

test('a failed descriptor save reverts the config file', async () => {
  const desc = makeServer({ worldNames: ['World', 'Second'] });
  const store = descriptorStore(desc, { failSave: true });
  const before = configOf(desc);
  const preview = worlds.previewSelect({ desc: store.desc, actorId: ACTOR, file: 'Second.wld', manager: fakeManager() });

  const { id, error } = await runOperation(worlds.KIND.SELECT, (operationId) => worlds.runSelect({
    desc: store.desc, manager: fakeManager(), operationId, preview,
    saveDescriptor: (fields) => store.saveDescriptor(fields),
    readDescriptor: () => store.readDescriptor(),
  }));
  assert.strictEqual(error.code, 'config_save_failed');
  assert.strictEqual(configOf(desc), before, 'the config file was not put back');
  assert.strictEqual(operations.get(id).state, 'failed', 'a compensated failure is failed, not recovery_required');
});

test('a selection that cannot be undone is recovery_required, never ok', async () => {
  const desc = makeServer({ worldNames: ['World', 'Second'] });
  const store = descriptorStore(desc);
  const preview = worlds.previewSelect({ desc: store.desc, actorId: ACTOR, file: 'Second.wld', manager: fakeManager() });

  // The descriptor save reports success and the re-read disagrees: the two halves
  // may now differ, and nothing may report that as a success.
  const { id, error } = await runOperation(worlds.KIND.SELECT, (operationId) => worlds.runSelect({
    desc: store.desc, manager: fakeManager(), operationId, preview,
    saveDescriptor: (fields) => store.saveDescriptor(fields),
    readDescriptor: () => ({ ...store.desc, terrariaWorld: null }),
  }));
  assert.strictEqual(error.code, 'verify_failed');
  const op = operations.get(id);
  assert.strictEqual(op.state, 'recovery_required');
  assert.ok(op.recovery && op.recovery.instructions, 'recovery instructions were not recorded');
});

test('a duplicated world= key blocks a selection instead of picking one', () => {
  const desc = makeServer({
    worldNames: ['World'],
    config: 'world=WORLDPATH/World.wld\nworldpath=WORLDPATH\nworld=WORLDPATH/Other.wld\n',
  });
  assert.throws(() => worlds.previewSelect({ desc, actorId: ACTOR, file: 'World.wld', manager: fakeManager() }),
    (err) => err.code === 'duplicate_key');
});

/* -------------------------------------------------------------- 6. import -- */

test('an uploaded world is imported with its .twld, and can select itself', async () => {
  const desc = makeServer({ worldNames: [], variant: 'tmodloader' });
  const store = descriptorStore(desc);
  const staged = stageUpload({ 'world.wld': worldBuffer(), 'world.twld': Buffer.alloc(64, 5) });

  const preview = await worlds.previewImport({
    desc: store.desc, actorId: ACTOR, staged, requestedName: 'Imported', select: true, manager: fakeManager(),
  });
  assert.strictEqual(preview.file, 'Imported.wld');
  assert.strictEqual(preview.modDataMissing, false);
  worlds.consumePreview({ token: preview.token, desc: store.desc, actorId: ACTOR, action: 'terraria-import' });

  const { result, error } = await runOperation(worlds.KIND.IMPORT, (operationId) => worlds.runImport({
    desc: store.desc, manager: fakeManager(), operationId, preview,
    saveDescriptor: (fields) => store.saveDescriptor(fields),
    readDescriptor: () => store.readDescriptor(),
  }));
  assert.ifError(error);
  assert.deepStrictEqual(result.companions, ['Imported.twld']);
  assert.ok(fs.existsSync(path.join(saveDirOf(desc), 'Imported.wld')));
  assert.ok(fs.existsSync(path.join(saveDirOf(desc), 'Imported.twld')), 'the .twld did not travel with the world');
  assert.strictEqual(store.desc.terrariaWorld.name, 'Imported');
  assert.match(configOf(desc), /world=.*Imported\.wld/);
  assert.strictEqual(fs.existsSync(staged.dir), false, 'staging was left behind');
});

test('a tModLoader import without its .twld says so before it runs', async () => {
  const desc = makeServer({ worldNames: [], variant: 'tmodloader' });
  const preview = await worlds.previewImport({
    desc, actorId: ACTOR, staged: stageUpload({ 'world.wld': worldBuffer() }), requestedName: 'Plain', manager: fakeManager(),
  });
  assert.strictEqual(preview.modDataMissing, true);
});

test('an import that is not a Terraria world is refused with a specific reason', async () => {
  const desc = makeServer({ worldNames: [] });
  const levelDat = Buffer.concat([Buffer.from([0x1f, 0x8b, 0x08, 0x00]), Buffer.alloc(64, 9)]);
  await rejects(() => worlds.previewImport({
    desc, actorId: ACTOR, staged: stageUpload({ 'world.wld': levelDat }), manager: fakeManager(),
  }), 'import_not_a_world');

  await rejects(() => worlds.previewImport({
    desc, actorId: ACTOR, staged: stageUpload({ 'world.wld': Buffer.alloc(6, 1) }), manager: fakeManager(),
  }), 'import_truncated');

  await rejects(() => worlds.previewImport({
    desc, actorId: ACTOR, staged: stageUpload({ 'world.wld': worldBuffer({ fileType: 3 }) }), manager: fakeManager(),
  }), 'import_player_file');

  await rejects(() => worlds.previewImport({
    desc, actorId: ACTOR, staged: stageUpload({ 'notes.txt': 'hello' }), manager: fakeManager(),
  }), 'world_missing');
});

test('an import onto an existing name is refused, never an overwrite', async () => {
  const desc = makeServer({ worldNames: ['World'] });
  const original = fs.readFileSync(path.join(saveDirOf(desc), 'World.wld'));
  await rejects(() => worlds.previewImport({
    desc, actorId: ACTOR, staged: stageUpload({ 'world.wld': worldBuffer({ revision: 99 }) }),
    requestedName: 'World', manager: fakeManager(),
  }), 'name_collision');
  assert.ok(original.equals(fs.readFileSync(path.join(saveDirOf(desc), 'World.wld'))), 'the existing world changed');
});

test('an archive import takes the one world it contains', async () => {
  const desc = makeServer({ worldNames: [] });
  const staged = stageUpload({ 'upload.zip': fs.readFileSync(makeZip(path.join(ROOT, `zip-${++seq}.zip`), [
    { name: 'Saves/Worlds/Adventure.wld', data: worldBuffer() },
    { name: 'Saves/Worlds/Adventure.twld', data: Buffer.alloc(32, 4) },
    { name: 'Saves/Players/Someone.plr', data: Buffer.alloc(16, 1) },
    { name: 'readme.txt', data: 'notes' },
  ])) }, { kind: 'archive' });

  const preview = await worlds.previewImport({ desc, actorId: ACTOR, staged, manager: fakeManager() });
  assert.strictEqual(preview.name, 'Adventure');
  assert.strictEqual(preview.source.modFile, 'Adventure.twld');
  // Only the world files were extracted: a player file is not ours to write.
  const extracted = fs.readdirSync(path.join(staged.dir, 'payload')).sort();
  assert.deepStrictEqual(extracted, ['Adventure.twld', 'Adventure.wld', 'upload.zip']);
});

test('a hostile or ambiguous archive is refused before anything is written', async () => {
  const desc = makeServer({ worldNames: [] });
  const cases = [
    ['path_traversal', [{ name: '../escape.wld', data: worldBuffer() }]],
    ['symlink', [{ name: 'link.wld', data: '/etc/passwd', mode: 0o120777 }]],
    ['absolute_path', [{ name: 'C:/worlds/evil.wld', data: worldBuffer() }]],
    ['multiple_worlds', [{ name: 'a.wld', data: worldBuffer() }, { name: 'b.wld', data: worldBuffer() }]],
  ];
  for (const [code, entries] of cases) {
    const staged = stageUpload({ 'upload.zip': fs.readFileSync(makeZip(path.join(ROOT, `hostile-${++seq}.zip`), entries)) }, { kind: 'archive' });
    const error = await rejects(() => worlds.previewImport({ desc, actorId: ACTOR, staged, manager: fakeManager() }), code);
    assert.ok(error);
    assert.deepStrictEqual(fs.readdirSync(saveDirOf(desc)), [], 'the save directory was written to');
  }
});

test('an over-limit archive is refused', async () => {
  const entries = Array.from({ length: 12 }, (_, i) => ({ name: `file${i}.txt`, data: 'x' }));
  const archive = makeZip(path.join(ROOT, `many-${++seq}.zip`), entries);
  const out = path.join(ROOT, `many-out-${seq}`);
  await rejects(() => worlds.extractWorldFromArchive(archive, out, { maxEntries: 4 }), 'too_many_entries');
  assert.deepStrictEqual(fs.readdirSync(out), [], 'entries were written past the limit');
});

/* ---------------------------------------------------------- 7. generation -- */

test('generation produces a verified world, promotes it, and can select it', async () => {
  const desc = makeServer({ worldNames: [], variant: 'tmodloader' });
  const store = descriptorStore(desc);
  const preview = worlds.previewGenerate({
    desc: store.desc, actorId: ACTOR, input: { name: 'Generated', size: 'small', difficulty: 'expert', seed: 'fleetdeck' },
    manager: fakeManager(),
  });
  assert.strictEqual(preview.autocreate, 1);
  assert.strictEqual(preview.difficultyValue, 1);
  worlds.consumePreview({ token: preview.token, desc: store.desc, actorId: ACTOR, action: 'terraria-generate' });

  const progress = [];
  const { id, result, error } = await runOperation(worlds.KIND.GENERATE, (operationId) => worlds.runGenerate({
    desc: store.desc, manager: fakeManager(), operationId, preview,
    saveDescriptor: (fields) => store.saveDescriptor(fields),
    readDescriptor: () => store.readDescriptor(),
    broadcast: (frame) => progress.push(frame),
    spawnGeneration: generationStub({ modData: true }),
  }));
  assert.ifError(error);
  assert.strictEqual(result.file, 'Generated.wld');
  assert.deepStrictEqual(result.companions, ['Generated.twld']);
  assert.strictEqual(operations.get(id).state, 'succeeded');
  assert.ok(fs.existsSync(path.join(saveDirOf(desc), 'Generated.wld')));
  assert.ok(fs.existsSync(path.join(saveDirOf(desc), 'Generated.twld')));
  assert.strictEqual(store.desc.terrariaWorld.name, 'Generated');
  assert.ok(progress.some((frame) => frame.type === 'terraria-worldgen' && frame.percent === 50), 'no progress was broadcast');
  noAbsolutePaths(progress, 'worldgen broadcast');
  // Staging is gone and the live config was never the generation config.
  assert.strictEqual(fs.existsSync(path.join(desc.dir, '.fleetdeck', 'staging', id)), false);
  assert.strictEqual((configOf(desc).match(/^autocreate=2$/m) || []).length, 1, 'the live config was rewritten');
});

test('generation writes into staging, never into the live save directory', async () => {
  const desc = makeServer({ worldNames: ['World'] });
  const store = descriptorStore(desc);
  const preview = worlds.previewGenerate({ desc: store.desc, actorId: ACTOR, input: { name: 'Fresh', size: 'medium', select: false }, manager: fakeManager() });
  let seen = null;
  await runOperation(worlds.KIND.GENERATE, (operationId) => worlds.runGenerate({
    desc: store.desc, manager: fakeManager(), operationId, preview,
    saveDescriptor: (fields) => store.saveDescriptor(fields),
    readDescriptor: () => store.readDescriptor(),
    spawnGeneration: generationStub({ onSpawn: ({ launch }) => { seen = launch; } }),
  }));
  // The argv is an array, the config is the staging one, and no world flag from
  // the descriptor survived to override it.
  assert.ok(Array.isArray(seen.args));
  const configArg = seen.args[seen.args.indexOf('-config') + 1];
  assert.match(configArg, /staging/);
  assert.strictEqual(seen.args.filter((arg) => arg === '-config').length, 1);
  // The selection was not taken, because the request said not to.
  assert.strictEqual(store.desc.terrariaWorld.name, 'World');
  assert.ok(fs.existsSync(path.join(saveDirOf(desc), 'Fresh.wld')));
});

test('a generation that produces nothing leaves the save directory untouched', async () => {
  const desc = makeServer({ worldNames: ['World'] });
  const store = descriptorStore(desc);
  const before = fs.readdirSync(saveDirOf(desc)).sort();
  const preview = worlds.previewGenerate({ desc: store.desc, actorId: ACTOR, input: { name: 'Nope', size: 'small' }, manager: fakeManager() });

  const { id, error } = await runOperation(worlds.KIND.GENERATE, (operationId) => worlds.runGenerate({
    desc: store.desc, manager: fakeManager(), operationId, preview,
    saveDescriptor: (fields) => store.saveDescriptor(fields),
    readDescriptor: () => store.readDescriptor(),
    spawnGeneration: generationStub({ produce: false }),
  }));
  assert.strictEqual(error.code, 'generate_failed');
  assert.strictEqual(operations.get(id).state, 'failed');
  assert.deepStrictEqual(fs.readdirSync(saveDirOf(desc)).sort(), before);
  assert.strictEqual(fs.existsSync(path.join(desc.dir, '.fleetdeck', 'staging', id)), false, 'staging was left behind');
});

test('a generation that produces an unreadable file is refused after the fact', async () => {
  const desc = makeServer({ worldNames: [] });
  const store = descriptorStore(desc);
  const preview = worlds.previewGenerate({ desc: store.desc, actorId: ACTOR, input: { name: 'Junk', size: 'small' }, manager: fakeManager() });
  const { error } = await runOperation(worlds.KIND.GENERATE, (operationId) => worlds.runGenerate({
    desc: store.desc, manager: fakeManager(), operationId, preview,
    saveDescriptor: (fields) => store.saveDescriptor(fields),
    readDescriptor: () => store.readDescriptor(),
    spawnGeneration: async ({ launch, onProgress }) => {
      onProgress({ percent: 100, stage: null });
      const document = terrariaConfig.parse(fs.readFileSync(launch.args[launch.args.indexOf('-config') + 1], 'utf8'));
      fs.writeFileSync(terrariaConfig.get(document, 'world'), Buffer.alloc(10, 1));
      return { code: 0 };
    },
  }));
  assert.strictEqual(error.code, 'generate_unreadable');
  assert.deepStrictEqual(fs.readdirSync(saveDirOf(desc)), []);
});

test('a cancelled generation leaves the save directory untouched', async () => {
  const desc = makeServer({ worldNames: [] });
  const store = descriptorStore(desc);
  const preview = worlds.previewGenerate({ desc: store.desc, actorId: ACTOR, input: { name: 'Cancelled', size: 'small' }, manager: fakeManager() });

  const { id, error } = await runOperation(worlds.KIND.GENERATE, (operationId) => worlds.runGenerate({
    desc: store.desc, manager: fakeManager(), operationId, preview,
    saveDescriptor: (fields) => store.saveDescriptor(fields),
    readDescriptor: () => store.readDescriptor(),
    spawnGeneration: async ({ operationId: opId }) => {
      operations.cancel(opId);
      throw new worlds.Cancelled();
    },
  }));
  assert.strictEqual(error.code, 'cancelled');
  assert.strictEqual(operations.get(id).state, 'cancelled');
  assert.deepStrictEqual(fs.readdirSync(saveDirOf(desc)), []);
});

test('generation inputs are validated, and a launcher script is never executed', () => {
  const desc = makeServer({ worldNames: [] });
  for (const input of [{ name: '../x' }, { name: 'Ok', size: 'huge' }, { name: 'Ok', difficulty: 'nightmare' }, { name: 'Ok', seed: 'bad;seed' }]) {
    assert.throws(() => worlds.previewGenerate({ desc, actorId: ACTOR, input, manager: fakeManager() }));
  }
  const wrapper = makeServer({ worldNames: [] });
  wrapper.executable = path.join(wrapper.dir, 'start-tModLoaderServer.sh');
  fs.writeFileSync(wrapper.executable, '#!/bin/sh\n');
  assert.throws(() => worlds.generationLaunch(wrapper, 'config.txt'), (err) => err.code === 'wrapper_refused');

  // Descriptor world flags are stripped so they cannot override the staging config.
  const flagged = makeServer({ worldNames: [] });
  flagged.args = ['-config', 'old.txt', '-world', '/somewhere/Other.wld', '-worldpath', '/somewhere', '-port', '7777'];
  const launch = worlds.generationLaunch(flagged, '/staging/config.txt');
  assert.deepStrictEqual(launch.args, ['-port', '7777', '-config', '/staging/config.txt']);
});

/* -------------------------------------------------------------- 8. delete -- */

test('deletion quarantines the world and its companions, and is restorable', async () => {
  const desc = makeServer({ worldNames: ['World', 'Second'], modData: true });
  desc.terrariaWorld = { file: 'worlds/Second.wld', name: 'Second' };
  const store = descriptorStore(desc);
  fs.writeFileSync(path.join(saveDirOf(desc), 'World.wld.bak'), worldBuffer());

  const preview = worlds.previewDelete({ desc: store.desc, actorId: ACTOR, file: 'World.wld', manager: fakeManager() });
  assert.deepStrictEqual(preview.companions.sort(), ['World.twld', 'World.wld.bak']);
  assert.strictEqual(preview.active, false);
  worlds.consumePreview({ token: preview.token, desc: store.desc, actorId: ACTOR, action: 'terraria-delete' });

  const { id, result, error } = await runOperation(worlds.KIND.DELETE, (operationId) => worlds.runDelete({
    desc: store.desc, manager: fakeManager(), operationId, preview, actorId: ACTOR,
    saveDescriptor: (fields) => store.saveDescriptor(fields),
    readDescriptor: () => store.readDescriptor(),
  }));
  assert.ifError(error);
  assert.strictEqual(operations.get(id).state, 'succeeded');
  assert.deepStrictEqual(fs.readdirSync(saveDirOf(desc)).sort(), ['Second.twld', 'Second.wld']);
  assert.strictEqual(result.trash.length, 3, 'not every file was quarantined');

  // Restorable, to exactly where each file came from.
  for (const entryId of result.trash) {
    const entry = trash.get(entryId);
    assert.strictEqual(entry.restorable, true, `${entry.label} is not restorable`);
    trash.restore(entryId);
  }
  assert.deepStrictEqual(fs.readdirSync(saveDirOf(desc)).sort(), ['Second.twld', 'Second.wld', 'World.twld', 'World.wld', 'World.wld.bak']);
});

test('deleting the selected world clears the selection in both places', async () => {
  const desc = makeServer({ worldNames: ['World'] });
  const store = descriptorStore(desc);
  const preview = worlds.previewDelete({ desc: store.desc, actorId: ACTOR, file: 'World.wld', manager: fakeManager() });
  assert.strictEqual(preview.active, true);
  assert.strictEqual(preview.clearsSelection, true);

  const { result, error } = await runOperation(worlds.KIND.DELETE, (operationId) => worlds.runDelete({
    desc: store.desc, manager: fakeManager(), operationId, preview, actorId: ACTOR,
    saveDescriptor: (fields) => store.saveDescriptor(fields),
    readDescriptor: () => store.readDescriptor(),
  }));
  assert.ifError(error);
  assert.strictEqual(result.selectionCleared, true);
  assert.strictEqual(store.desc.terrariaWorld, undefined);
  assert.ok(!/^world=/m.test(configOf(desc)), 'world= still points at the deleted file');
  // Everything else in the config survived.
  assert.match(configOf(desc), /^worldpath=/m);
  assert.match(configOf(desc), /^motd=Hello$/m);
});

test('an unreadable world can still be deleted', async () => {
  const desc = makeServer({ worldNames: ['World'] });
  fs.writeFileSync(path.join(saveDirOf(desc), 'Broken.wld'), Buffer.alloc(4, 1));
  const store = descriptorStore(desc);
  const preview = worlds.previewDelete({ desc: store.desc, actorId: ACTOR, file: 'Broken.wld', manager: fakeManager() });
  assert.strictEqual(preview.world.readable, false);
  const { error } = await runOperation(worlds.KIND.DELETE, (operationId) => worlds.runDelete({
    desc: store.desc, manager: fakeManager(), operationId, preview, actorId: ACTOR,
    saveDescriptor: (fields) => store.saveDescriptor(fields),
    readDescriptor: () => store.readDescriptor(),
  }));
  assert.ifError(error);
  assert.strictEqual(fs.existsSync(path.join(saveDirOf(desc), 'Broken.wld')), false);
});

/* --------------------------------------------------- 9. shared guarantees -- */

test('every mutation is refused while the server is not offline', async () => {
  const desc = makeServer({ worldNames: ['World', 'Second'] });
  const store = descriptorStore(desc);
  const online = fakeManager('online');

  const select = worlds.previewSelect({ desc: store.desc, actorId: ACTOR, file: 'Second.wld', manager: online });
  assert.strictEqual(select.serverOffline, false);
  const generate = worlds.previewGenerate({ desc: store.desc, actorId: ACTOR, input: { name: 'New', size: 'small' }, manager: online });
  const del = worlds.previewDelete({ desc: store.desc, actorId: ACTOR, file: 'World.wld', manager: online });
  const importPreview = await worlds.previewImport({
    desc: store.desc, actorId: ACTOR, staged: stageUpload({ 'world.wld': worldBuffer() }), requestedName: 'Fresh', manager: online,
  });

  const access = {
    saveDescriptor: (fields) => store.saveDescriptor(fields),
    readDescriptor: () => store.readDescriptor(),
  };
  const runs = [
    ['select', (operationId) => worlds.runSelect({ desc: store.desc, manager: online, operationId, preview: select, ...access })],
    ['generate', (operationId) => worlds.runGenerate({ desc: store.desc, manager: online, operationId, preview: generate, spawnGeneration: generationStub(), ...access })],
    ['delete', (operationId) => worlds.runDelete({ desc: store.desc, manager: online, operationId, preview: del, actorId: ACTOR, ...access })],
    ['import', (operationId) => worlds.runImport({ desc: store.desc, manager: online, operationId, preview: importPreview, ...access })],
  ];
  for (const [label, run] of runs) {
    const { error } = await runOperation(worlds.KIND.SELECT, run);
    assert.strictEqual(error && error.code, 'server_online', `${label} ran against a running server`);
  }
  assert.deepStrictEqual(fs.readdirSync(saveDirOf(desc)).sort(), ['Second.wld', 'World.wld']);
});

test('insufficient disk space aborts before any write', async () => {
  const desc = makeServer({ worldNames: ['World'] });
  const store = descriptorStore(desc);
  const preview = worlds.previewDelete({ desc: store.desc, actorId: ACTOR, file: 'World.wld', manager: fakeManager() });
  // An unknown capacity must read as "no", not as "there is room".
  const unknown = worlds.diskPlan(path.join(ROOT, 'does-not-exist'), 1024);
  assert.strictEqual(unknown.sufficient, false);
  assert.strictEqual(unknown.reason, 'capacity_unknown');
  assert.throws(() => worlds.assertDisk(unknown), (err) => err.code === 'capacity_unknown');

  const impossible = { ...preview, disk: { ...preview.disk, requiredBytes: Number.MAX_SAFE_INTEGER } };
  const { error } = await runOperation(worlds.KIND.DELETE, (operationId) => worlds.runDelete({
    desc: store.desc, manager: fakeManager(), operationId, preview: impossible, actorId: ACTOR,
    saveDescriptor: (fields) => store.saveDescriptor(fields),
    readDescriptor: () => store.readDescriptor(),
  }));
  assert.strictEqual(error.code, 'insufficient_space');
  assert.ok(fs.existsSync(path.join(saveDirOf(desc), 'World.wld')));
});

test('every mutation kind is destructive, so an interrupted one needs recovery', () => {
  for (const kind of Object.values(worlds.KIND)) {
    assert.ok(operations.isDestructiveKind(kind), `${kind} is not treated as destructive`);
  }
  const op = operations.create({ kind: worlds.KIND.IMPORT, actorId: ACTOR, serverId: `sweep-${++seq}` });
  operations.start(op.id, { phase: 'commit' });
  const swept = operations.sweepStale({ heartbeatStaleMs: -1 });
  const mine = swept.find((entry) => entry.id === op.id);
  assert.strictEqual(mine.state, 'recovery_required');
  assert.ok(mine.recovery, 'no recovery instructions were recorded');
});

test('a run that fails in its own setup still ends as a recorded failure', async () => {
  // The world folder stops resolving between the preview and the apply. The
  // operation has to become a terminal failure: one that stayed `running` would
  // hold the per-server lock until a boot sweep found it.
  const desc = makeServer({ worldNames: ['World', 'Second'] });
  const store = descriptorStore(desc);
  const preview = worlds.previewSelect({ desc: store.desc, actorId: ACTOR, file: 'Second.wld', manager: fakeManager() });
  delete store.desc.terrariaSaveDir;
  fs.writeFileSync(path.join(desc.dir, 'serverconfig.txt'), '# the worldpath is gone\nport=7777\n');

  const { id, error } = await runOperation(worlds.KIND.SELECT, (operationId) => worlds.runSelect({
    desc: store.desc, manager: fakeManager(), operationId, preview,
    saveDescriptor: (fields) => store.saveDescriptor(fields),
    readDescriptor: () => store.readDescriptor(),
  }));
  assert.strictEqual(error.code, 'save_dir_unknown');
  assert.strictEqual(operations.get(id).state, 'failed');
});

test('a verified snapshot is taken before every destructive run', async () => {
  const desc = makeServer({ worldNames: ['World', 'Second'] });
  const store = descriptorStore(desc);
  const taken = [];
  const realTake = snapshots.take;
  snapshots.take = (args) => { taken.push(args); return realTake(args); };
  try {
    const preview = worlds.previewSelect({ desc: store.desc, actorId: ACTOR, file: 'Second.wld', manager: fakeManager() });
    await runOperation(worlds.KIND.SELECT, (operationId) => worlds.runSelect({
      desc: store.desc, manager: fakeManager(), operationId, preview,
      saveDescriptor: (fields) => store.saveDescriptor(fields),
      readDescriptor: () => store.readDescriptor(),
    }));
    const del = worlds.previewDelete({ desc: store.desc, actorId: ACTOR, file: 'World.wld', manager: fakeManager() });
    await runOperation(worlds.KIND.DELETE, (operationId) => worlds.runDelete({
      desc: store.desc, manager: fakeManager(), operationId, preview: del, actorId: ACTOR,
      saveDescriptor: (fields) => store.saveDescriptor(fields),
      readDescriptor: () => store.readDescriptor(),
    }));
  } finally {
    snapshots.take = realTake;
  }
  assert.strictEqual(taken.length, 2, 'a run went ahead without a snapshot');
  assert.deepStrictEqual(taken[0].scope, ['serverconfig.txt']);
  assert.deepStrictEqual(taken[1].scope, ['worlds']);
});

test('a download carries the world and its companions', async () => {
  const desc = makeServer({ worldNames: ['World'], modData: true });
  const plan = worlds.downloadName(desc, 'World.wld');
  assert.match(plan.filename, /^Server-srv-\d+-World-\d{4}-\d{2}-\d{2}T/);
  assert.deepStrictEqual(plan.files.sort(), ['World.twld', 'World.wld']);

  const out = path.join(ROOT, `download-${++seq}.zip`);
  const result = await worlds.zipWorld(desc, 'World.wld', fs.createWriteStream(out));
  assert.deepStrictEqual(result.files.sort(), ['World.twld', 'World.wld']);
  assert.ok(fs.statSync(out).size > 0);
});

/* ---------------------------------------------- 10. the config serializer -- */

test('a no-op parse and serialize is byte-identical, for every shape', () => {
  const shapes = [
    'a=1\nb=2\n',
    'a=1\r\nb=2\r\n',
    '\ufefflead=1\n',
    '# comment\n\n  spaced = value  \nempty=\n',
    'no-trailing-newline=1',
    'mixed=1\r\nendings=2\n',
    'value=has=equals\nnonascii=Zoë Müller\n',
    '',
  ];
  for (const text of shapes) {
    assert.strictEqual(terrariaConfig.serialize(terrariaConfig.parse(text)), text, `round trip changed ${JSON.stringify(text)}`);
  }
});

test('a one-key edit changes only that line', () => {
  const text = '# header\r\nworld=old\r\n\r\nmotd=hi\r\n';
  const { document, diff } = terrariaConfig.patch(terrariaConfig.parse(text), { world: 'new' });
  assert.deepStrictEqual(diff, [{ key: 'world', from: 'old', to: 'new' }]);
  assert.strictEqual(terrariaConfig.serialize(document), '# header\r\nworld=new\r\n\r\nmotd=hi\r\n');

  // An absent key is appended with the file's own line ending; a removal takes
  // the whole line.
  const appended = terrariaConfig.patch(terrariaConfig.parse(text), { seed: 'x' });
  assert.strictEqual(terrariaConfig.serialize(appended.document), `${text}seed=x\r\n`);
  const removed = terrariaConfig.patch(terrariaConfig.parse(text), { world: null });
  assert.strictEqual(terrariaConfig.serialize(removed.document), '# header\r\n\r\nmotd=hi\r\n');
});

test('a duplicated key is refused rather than resolved, and a line break is never written', () => {
  const document = terrariaConfig.parse('world=a\nworld=b\n');
  assert.throws(() => terrariaConfig.patch(document, { world: 'c' }), (err) => err.code === 'duplicate_key');
  assert.throws(() => terrariaConfig.get(document, 'world'), (err) => err.code === 'duplicate_key');
  assert.throws(() => terrariaConfig.patch(terrariaConfig.parse('a=1\n'), { a: 'x\ny=2' }), (err) => err.code === 'invalid_value');
  // Whitespace around a key and its separator survives an edit.
  const spaced = terrariaConfig.patch(terrariaConfig.parse('  world =  old\n'), { world: 'new' });
  assert.strictEqual(terrariaConfig.serialize(spaced.document), '  world =  new\n');
});

/* ------------------------------------------------------------------- run -- */

(async () => {
  let failed = 0;
  for (const entry of tests) {
    try { await entry.fn(); console.log(`ok  ${entry.name}`); }
    catch (error) { failed++; console.error(`FAIL  ${entry.name}: ${error.message}\n${error.stack}`); }
  }
  close();
  try { fs.rmSync(ROOT, { recursive: true, force: true }); } catch (_) { /* */ }
  teardown();
  if (failed) { console.error(`FAIL  ${failed} of ${tests.length} terraria-worlds test(s) failed`); process.exit(1); }
  console.log(`PASS  terraria-worlds (${tests.length} tests)`);
})();
